package entity

const ROOMS_IN_WIDTH = 3
const ROOMS_IN_HEIGHT = 3
const ROOMS_NUM = (ROOMS_IN_WIDTH * ROOMS_IN_HEIGHT)
const MAX_PASSAGE_PARTS = 3
const MAX_PASSAGES_NUM = ((ROOMS_NUM - 1) * MAX_PASSAGE_PARTS)

const REGION_WIDTH = 27
const REGION_HEIGHT = 10
const MIN_ROOM_WIDTH = 6
const MAX_ROOM_WIDTH = (REGION_WIDTH - 2)
const MIN_ROOM_HEIGHT = 5
const MAX_ROOM_HEIGHT = (REGION_HEIGHT - 2)

const CONSUMABLES_TYPES_NUM = 4
const CONSUMABLES_TYPE_MAX_NUM = 9
const CONSUMABLES_NUM = CONSUMABLES_TYPES_NUM * CONSUMABLES_TYPE_MAX_NUM

const NO_WEAPON = 0

const MAX_NAME_LEN = (32 + 1)

const MAX_PERCENT_FOOD_REGEN_FROM_HEALTH = 20
const MAX_PERCENT_AGILITY_INCREASE = 10
const MAX_PERCENT_STRENGTH_INCREASE = 10

const MIN_ELIXIR_DURATION_SECONDS = 30
const MAX_ELIXIR_DURATION_SECONDS = 60

const MIN_WEAPON_STRENGTH = 30
const MAX_WEAPON_STRENGTH = 50

const LOW_HOSTILITY_RADIUS = 2
const AVERAGE_HOSTILITY_RADIUS = 4
const HIGH_HOSTILITY_RADIUS = 6

const MAX_CONSUMABLES_PER_ROOM = 3
const MAX_MONSTERS_PER_ROOM = 2
const MAX_DOORS_PER_LEVEL = ROOMS_NUM * 2

const LEVEL_UPDATE_DIFFICULTY = 10
const PERCENTS_UPDATE_DIFFICULTY_MONSTERS = 2

const LEVEL_NUM = 21